export const  drugDetails = [
    { 
      id: 1,
      name: 'Nexium',
      price: 22 ,
      image:'https://media.npr.org/assets/img/2015/05/01/gettyimages-453912462_wide-3f50a25f9547a945aae1ba61d57ab175500d9d93.jpg',
      description: 'Nexium is a proton pump inhibitor that decreases the amount of acid produced in the stomach.Nexium is used to treat symptoms of gastroesophageal reflux disease (GERD) and other conditions involving excessive stomach acid such as Zollinger-Ellison syndrome. It is also used to promote healing of erosive esophagitis (damage to your esophagus caused by stomach acid).Nexium may also be given to prevent gastric ulcer caused by infection with Helicobacter pylori (H. pylori), or by the use of nonsteroidal anti-inflammatory drugs (NSAIDs).',
      sideEffects: 'Get emergency medical help if you have signs of an allergic reaction ro Nexium: hives; difficulty breathing; swelling of your face, lips, tongue, or throat.',
      dosage: 'Take each dose with a full glass (8 ounces) of water. Nexium should be taken at least one hour before a meal.Do not crush or chew a delayed-release capsule. However to make swallowing easier, you may open the capsule and sprinkle the medicine into a spoonful of pudding or applesauce. Swallow right away without chewing. Do not save the mixture for later use.',
    },
    { 
      id: 2,
      price: 17,
      name: 'Generic Drug 1',
      image:'https://149918304.v2.pressablecdn.com/wp-content/uploads/2022/08/Prescription-Drug-scaled-1-1024x683-4959255.jpeg',
      description: 'A generic drug 1 is a drug that is not branded but is similar to a branded or reference listed drug in terms of dosage, administration and performance.According to guidelines from the United States Food and Drug Administration (FDA), the generic drug must have the same active ingredient as the brand name drug as well as the same dosage, strength, safety, conditions of use and route of administration.',
      sideEffects: 'An allergic reaction could happen with any drug. That can range from itching and rash all the way to a life-threatening anaphylactic reaction.',
      dosage: 'Drug in dosage form, safety, strength, route of administration, quality, performance characteristics,  intended use.',
    },
    { 
      id: 3,
      price: 21,
      name: 'Generic Drug 2',
      image:'https://domf5oio6qrcr.cloudfront.net/medialibrary/4977/3687af9d-7e14-43ee-999b-7c9f3a341b9d.jpg',
      description: 'A generic drug 2 is a drug that is not branded but is similar to a branded or reference listed drug in terms of dosage, administration and performance.According to guidelines from the United States Food and Drug Administration (FDA), the generic drug must have the same active ingredient as the brand name drug as well as the same dosage, strength, safety, conditions of use and route of administration.',
      sideEffects: 'An allergic reaction could happen with any drug. That can range from itching and rash all the way to a life-threatening anaphylactic reaction.',
      dosage: 'Drug in dosage form, safety, strength, route of administration, quality, performance characteristics,  intended use.',
    },
    { 
      id: 4,
      price: 21,
      name: 'Lenalidomide',
      image:'https://5.imimg.com/data5/KY/BR/MY-6964226/lenalid-10-mg-capsules-500x500.jpg',
      description: 'Lenalidomide is a proton pump inhibitor that decreases the amount of acid produced in the stomach.Nexium is used to treat symptoms of gastroesophageal reflux disease (GERD) and other conditions involving excessive stomach acid such as Zollinger-Ellison syndrome. It is also used to promote healing of erosive esophagitis (damage to your esophagus caused by stomach acid).Nexium may also be given to prevent gastric ulcer caused by infection with Helicobacter pylori (H. pylori), or by the use of nonsteroidal anti-inflammatory drugs (NSAIDs).',
      sideEffects: 'Get emergency medical help if you have signs of an allergic reaction ro Nexium: hives; difficulty breathing; swelling of your face, lips, tongue, or throat.',
      dosage: 'Take each dose with a full glass (8 ounces) of water. Nexium should be taken at least one hour before a meal.Do not crush or chew a delayed-release capsule. However to make swallowing easier, you may open the capsule and sprinkle the medicine into a spoonful of pudding or applesauce. Swallow right away without chewing. Do not save the mixture for later use.',
 
    },
    { 
      id: 5,
      price: 15,
      name: 'Concerta',
      image:'https://media.sciencephoto.com/c0/16/72/82/c0167282-800px-wm.jpg',
      description: 'A Concerta is a drug that is not branded but is similar to a branded or reference listed drug in terms of dosage, administration and performance.According to guidelines from the United States Food and Drug Administration (FDA), the generic drug must have the same active ingredient as the brand name drug as well as the same dosage, strength, safety, conditions of use and route of administration.',
      sideEffects: 'An allergic reaction could happen with any drug. That can range from itching and rash all the way to a life-threatening anaphylactic reaction.',
      dosage: 'Drug in dosage form, safety, strength, route of administration, quality, performance characteristics,  intended use.',
    },
    { 
      id: 6,
      price: 29,
      name: 'Xtandi',
      image:'https://www.mmm-online.com/wp-content/uploads/sites/2/2018/08/xtandi_945224.jpg',
      description: 'Xtandi is a proton pump inhibitor that decreases the amount of acid produced in the stomach.Nexium is used to treat symptoms of gastroesophageal reflux disease (GERD) and other conditions involving excessive stomach acid such as Zollinger-Ellison syndrome. It is also used to promote healing of erosive esophagitis (damage to your esophagus caused by stomach acid).Nexium may also be given to prevent gastric ulcer caused by infection with Helicobacter pylori (H. pylori), or by the use of nonsteroidal anti-inflammatory drugs (NSAIDs).',
      sideEffects: 'Get emergency medical help if you have signs of an allergic reaction ro Nexium: hives; difficulty breathing; swelling of your face, lips, tongue, or throat.',
      dosage: 'Take each dose with a full glass (8 ounces) of water. Nexium should be taken at least one hour before a meal.Do not crush or chew a delayed-release capsule. However to make swallowing easier, you may open the capsule and sprinkle the medicine into a spoonful of pudding or applesauce. Swallow right away without chewing. Do not save the mixture for later use.',
    },
    { 
      id: 7,
      price: 18,
      name: 'Rx drug',
      image:'https://t4.ftcdn.net/jpg/02/87/86/27/360_F_287862773_eVjRtEA5jOYUKywa9xy9kunFr4BquZdO.jpg',
     description: 'A  Rx drug is a drug that is not branded but is similar to a branded or reference listed drug in terms of dosage, administration and performance.According to guidelines from the United States Food and Drug Administration (FDA), the generic drug must have the same active ingredient as the brand name drug as well as the same dosage, strength, safety, conditions of use and route of administration.',
      sideEffects: 'An allergic reaction could happen with any drug. That can range from itching and rash all the way to a life-threatening anaphylactic reaction.',
      dosage: 'Drug in dosage form, safety, strength, route of administration, quality, performance characteristics,  intended use.'
    },
    { 
      id: 8,
      price: 23,
      name: 'Amoxicillin',
      image:'https://5.imimg.com/data5/SELLER/Default/2022/7/GY/WG/RO/51330036/new-product-500x500.jpeg',
      description: 'Amoxicillin is a proton pump inhibitor that decreases the amount of acid produced in the stomach.Nexium is used to treat symptoms of gastroesophageal reflux disease (GERD) and other conditions involving excessive stomach acid such as Zollinger-Ellison syndrome. It is also used to promote healing of erosive esophagitis (damage to your esophagus caused by stomach acid).Nexium may also be given to prevent gastric ulcer caused by infection with Helicobacter pylori (H. pylori), or by the use of nonsteroidal anti-inflammatory drugs (NSAIDs).',
      sideEffects: 'Get emergency medical help if you have signs of an allergic reaction ro Nexium: hives; difficulty breathing; swelling of your face, lips, tongue, or throat.',
      dosage: 'Take each dose with a full glass (8 ounces) of water. Nexium should be taken at least one hour before a meal.Do not crush or chew a delayed-release capsule. However to make swallowing easier, you may open the capsule and sprinkle the medicine into a spoonful of pudding or applesauce. Swallow right away without chewing. Do not save the mixture for later use.',
    },
    { 
      id: 9,
      price: 10.0,
      name: 'Ivermectin',
      image:'https://independentnews.co.sz/wp-content/uploads/2021/02/file-20210205-21-1g1yuct.jpg',
      description: 'Ivermectin is a proton pump inhibitor that decreases the amount of acid produced in the stomach.Nexium is used to treat symptoms of gastroesophageal reflux disease (GERD) and other conditions involving excessive stomach acid such as Zollinger-Ellison syndrome. It is also used to promote healing of erosive esophagitis (damage to your esophagus caused by stomach acid).Nexium may also be given to prevent gastric ulcer caused by infection with Helicobacter pylori (H. pylori), or by the use of nonsteroidal anti-inflammatory drugs (NSAIDs).',
      sideEffects: 'Get emergency medical help if you have signs of an allergic reaction ro Ivermectin: hives; difficulty breathing; swelling of your face, lips, tongue, or throat.',
      dosage: 'Take each dose with a full glass (8 ounces) of water. Ivermectin should be taken at least one hour before a meal.Do not crush or chew a delayed-release capsule. However to make swallowing easier, you may open the capsule and sprinkle the medicine into a spoonful of pudding or applesauce. Swallow right away without chewing. Do not save the mixture for later use.',
    },
    { 
      id: 10,
      name: 'Amikacin',
      price: 20.0,
      image:'https://5.imimg.com/data5/SELLER/Default/2022/8/OX/MY/YA/46457290/amikacin-500-methyl-paraben-0-18-w-v-propyl-paraben-0-02-w-v-2ml-vial-zenikacin-500-500x500.jpg',
      description: 'A Amikacin 1 is a drug that is not branded but is similar to a branded or reference listed drug in terms of dosage, administration and performance.According to guidelines from the United States Food and Drug Administration (FDA), the generic drug must have the same active ingredient as the brand name drug as well as the same dosage, strength, safety, conditions of use and route of administration.',
      sideEffects: 'An allergic reaction could happen with any drug. That can range from itching and rash all the way to a life-threatening anaphylactic reaction.',
      dosage: 'Drug in dosage form, safety, strength, route of administration, quality, performance characteristics,  intended use.',
    },
    { 
      id: 11,
      price: 40.0,
      name: 'Delamanid',
      image:'https://5.imimg.com/data5/SELLER/Default/2022/4/ML/KY/KT/147809161/deltyba-1.png',
      description: 'A Delamanid is a drug that is not branded but is similar to a branded or reference listed drug in terms of dosage, administration and performance.According to guidelines from the United States Food and Drug Administration (FDA), the generic drug must have the same active ingredient as the brand name drug as well as the same dosage, strength, safety, conditions of use and route of administration.',
      sideEffects: 'An allergic reaction could happen with any drug. That can range from itching and rash all the way to a life-threatening anaphylactic reaction.',
      dosage: 'Drug in dosage form, safety, strength, route of administration, quality, performance characteristics,  intended use.',
    },
    { 
      id: 12,
      price: 55.0,
      name: 'Terbinafine',
      image:'https://5.imimg.com/data5/KY/BR/MY-6964226/lenalid-10-mg-capsules-500x500.jpg',
      description: 'Terbinafine is a proton pump inhibitor that decreases the amount of acid produced in the stomach.Nexium is used to treat symptoms of gastroesophageal reflux disease (GERD) and other conditions involving excessive stomach acid such as Zollinger-Ellison syndrome. It is also used to promote healing of erosive esophagitis (damage to your esophagus caused by stomach acid).Nexium may also be given to prevent gastric ulcer caused by infection with Helicobacter pylori (H. pylori), or by the use of nonsteroidal anti-inflammatory drugs (NSAIDs).',
      sideEffects: 'Get emergency medical help if you have signs of an allergic reaction roTerbinafine: hives; difficulty breathing; swelling of your face, lips, tongue, or throat.',
      dosage: 'Take each dose with a full glass (8 ounces) of water. Terbinafine should be taken at least one hour before a meal.Do not crush or chew a delayed-release capsule. However to make swallowing easier, you may open the capsule and sprinkle the medicine into a spoonful of pudding or applesauce. Swallow right away without chewing. Do not save the mixture for later use.',
 
    },
    { 
      id: 13,
      price: 34.0,
      name: 'ClovirValganci',
      image:'https://5.imimg.com/data5/SELLER/Default/2022/1/YX/BY/OZ/133780755/sustiva-efavirenz-tablets-500x500.jpg',
      description: 'A ClovirValganci is a drug that is not branded but is similar to a branded or reference listed drug in terms of dosage, administration and performance.According to guidelines from the United States Food and Drug Administration (FDA), the generic drug must have the same active ingredient as the brand name drug as well as the same dosage, strength, safety, conditions of use and route of administration.',
      sideEffects: 'An allergic reaction could happen with any drug. That can range from itching and rash all the way to a life-threatening anaphylactic reaction.',
      dosage: 'Drug in dosage form, safety, strength, route of administration, quality, performance characteristics,  intended use.',
    },
    { 
      id: 14,
      price: 28.0,
      name: 'Lamivudine',
      image:'https://5.imimg.com/data5/SELLER/Default/2022/2/TP/WF/EF/113955293/avonza-tablets-500x500.png',
      description: 'Lamivudine is a proton pump inhibitor that decreases the amount of acid produced in the stomach.Nexium is used to treat symptoms of gastroesophageal reflux disease (GERD) and other conditions involving excessive stomach acid such as Zollinger-Ellison syndrome. It is also used to promote healing of erosive esophagitis (damage to your esophagus caused by stomach acid).Nexium may also be given to prevent gastric ulcer caused by infection with Helicobacter pylori (H. pylori), or by the use of nonsteroidal anti-inflammatory drugs (NSAIDs).',
      sideEffects: 'Get emergency medical help if you have signs of an allergic reaction ro Nexium: hives; difficulty breathing; swelling of your face, lips, tongue, or throat.',
      dosage: 'Take each dose with a full glass (8 ounces) of water. Nexium should be taken at least one hour before a meal.Do not crush or chew a delayed-release capsule. However to make swallowing easier, you may open the capsule and sprinkle the medicine into a spoonful of pudding or applesauce. Swallow right away without chewing. Do not save the mixture for later use.',
    },
    { 
      id: 15,
      price: 98.0, 
      name: 'Daclatasvi',
      image:'https://www.healthizalife.com/wp-content/uploads/2022/04/Abacavir-Tablets-4.jpg',
     description: 'A  Daclatasvi is a drug that is not branded but is similar to a branded or reference listed drug in terms of dosage, administration and performance.According to guidelines from the United States Food and Drug Administration (FDA), the generic drug must have the same active ingredient as the brand name drug as well as the same dosage, strength, safety, conditions of use and route of administration.',
      sideEffects: 'An allergic reaction could happen with any drug. That can range from itching and rash all the way to a life-threatening anaphylactic reaction.',
      dosage: 'Drug in dosage form, safety, strength, route of administration, quality, performance characteristics,  intended use.'
    },
    { 
      id: 16,
      name: 'Lenalidomide',
      price: 76.0,
      image:'https://www.mbapharmaceuticals.com/wp-content/uploads/2020/01/LIDOMIDE-25-NEW-PACK.png',
      description: 'Lenalidomide is a proton pump inhibitor that decreases the amount of acid produced in the stomach.Nexium is used to treat symptoms of gastroesophageal reflux disease (GERD) and other conditions involving excessive stomach acid such as Zollinger-Ellison syndrome. It is also used to promote healing of erosive esophagitis (damage to your esophagus caused by stomach acid).Nexium may also be given to prevent gastric ulcer caused by infection with Helicobacter pylori (H. pylori), or by the use of nonsteroidal anti-inflammatory drugs (NSAIDs).',
      sideEffects: 'Get emergency medical help if you have signs of an allergic reaction ro Lenalidomide: hives; difficulty breathing; swelling of your face, lips, tongue, or throat.',
      dosage: 'Take each dose with a full glass (8 ounces) of water. Lenalidomide should be taken at least one hour before a meal.Do not crush or chew a delayed-release capsule. However to make swallowing easier, you may open the capsule and sprinkle the medicine into a spoonful of pudding or applesauce. Swallow right away without chewing. Do not save the mixture for later use.',
    },
    { 
      id: 17,
      price: 34.0,
      name: 'Dabigatran',
      image:'https://5.imimg.com/data5/SELLER/Default/2022/9/NK/CN/CF/3468355/pradaxa-dabigatran-medicine-.jpg',
      description: 'Dabigatran is a proton pump inhibitor that decreases the amount of acid produced in the stomach.Nexium is used to treat symptoms of gastroesophageal reflux disease (GERD) and other conditions involving excessive stomach acid such as Zollinger-Ellison syndrome. It is also used to promote healing of erosive esophagitis (damage to your esophagus caused by stomach acid).Nexium may also be given to prevent gastric ulcer caused by infection with Helicobacter pylori (H. pylori), or by the use of nonsteroidal anti-inflammatory drugs (NSAIDs).',
      sideEffects: 'Get emergency medical help if you have signs of an allergic reaction ro Dabigatran: hives; difficulty breathing; swelling of your face, lips, tongue, or throat.',
      dosage: 'Take each dose with a full glass (8 ounces) of water. Dabigatran should be taken at least one hour before a meal.Do not crush or chew a delayed-release capsule. However to make swallowing easier, you may open the capsule and sprinkle the medicine into a spoonful of pudding or applesauce. Swallow right away without chewing. Do not save the mixture for later use.',
    },
    { 
      id: 18,
      price: 47.0,
      name: 'Insulin Glargine',
      image:'https://5.imimg.com/data5/SELLER/Default/2020/12/QT/YX/VR/115213003/lantus-insulin-glargine-injection-500x500.jpg',
      description: 'A Insulin Glargine is a drug that is not branded but is similar to a branded or reference listed drug in terms of dosage, administration and performance.According to guidelines from the United States Food and Drug Administration (FDA), the generic drug must have the same active ingredient as the brand name drug as well as the same dosage, strength, safety, conditions of use and route of administration.',
      sideEffects: 'An allergic reaction could happen with any drug. That can range from itching and rash all the way to a life-threatening anaphylactic reaction.',
      dosage: 'Drug in dosage form, safety, strength, route of administration, quality, performance characteristics,  intended use.',
    },
    { 
      id: 19,
      price: 83.0,
      name: 'Montelukast',
      image:'https://greenpharmacyonline.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/1/6/16729011910_3.jpg',
      description: 'A generic drug 2 is a drug that is not branded but is similar to a branded or reference listed drug in terms of dosage, administration and performance.According to guidelines from the United States Food and Drug Administration (FDA), the generic drug must have the same active ingredient as the brand name drug as well as the same dosage, strength, safety, conditions of use and route of administration.',
      sideEffects: 'An allergic reaction could happen with any drug. That can range from itching and rash all the way to a life-threatening anaphylactic reaction.',
      dosage: 'Drug in dosage form, safety, strength, route of administration, quality, performance characteristics,  intended use.',
    },
    { 
      id: 20,
      price: 67.0,
      name: 'Rotavirus Cap',
      image:'https://etimg.etb2bimg.com/photo/70713070.cms',
      description: 'Rotavirus Cap is a proton pump inhibitor that decreases the amount of acid produced in the stomach.Nexium is used to treat symptoms of gastroesophageal reflux disease (GERD) and other conditions involving excessive stomach acid such as Zollinger-Ellison syndrome. It is also used to promote healing of erosive esophagitis (damage to your esophagus caused by stomach acid).Nexium may also be given to prevent gastric ulcer caused by infection with Helicobacter pylori (H. pylori), or by the use of nonsteroidal anti-inflammatory drugs (NSAIDs).',
      sideEffects: 'Get emergency medical help if you have signs of an allergic reaction ro Rotavirus Cap: hives; difficulty breathing; swelling of your face, lips, tongue, or throat.',
      dosage: 'Take each dose with a full glass (8 ounces) of water. Rotavirus Cap should be taken at least one hour before a meal.Do not crush or chew a delayed-release capsule. However to make swallowing easier, you may open the capsule and sprinkle the medicine into a spoonful of pudding or applesauce. Swallow right away without chewing. Do not save the mixture for later use.',
 
    },
    { 
      id: 21,
      price: 90.0,
      name: 'Cefuroxime',
      image:'https://wellonapharma.com/admincms/product_img/product_resize_img/cefuroxime-injection_1486638860.jpg',
      description: 'A Cefuroxime is a drug that is not branded but is similar to a branded or reference listed drug in terms of dosage, administration and performance.According to guidelines from the United States Food and Drug Administration (FDA), the generic drug must have the same active ingredient as the brand name drug as well as the same dosage, strength, safety, conditions of use and route of administration.',
      sideEffects: 'An allergic reaction could happen with any drug. That can range from itching and rash all the way to a life-threatening anaphylactic reaction.',
      dosage: 'Drug in dosage form, safety, strength, route of administration, quality, performance characteristics,  intended use.',
    },
    { 
      id: 22,
      price: 70.0,
      name: 'Bedaquiline',
      image:'https://cms.swasth-egurukul.in/sites/default/files/bdq.jpeg',
      description: 'Bedaquiline is a proton pump inhibitor that decreases the amount of acid produced in the stomach.Nexium is used to treat symptoms of gastroesophageal reflux disease (GERD) and other conditions involving excessive stomach acid such as Zollinger-Ellison syndrome. It is also used to promote healing of erosive esophagitis (damage to your esophagus caused by stomach acid).Nexium may also be given to prevent gastric ulcer caused by infection with Helicobacter pylori (H. pylori), or by the use of nonsteroidal anti-inflammatory drugs (NSAIDs).',
      sideEffects: 'Get emergency medical help if you have signs of an allergic reaction ro Nexium: hives; difficulty breathing; swelling of your face, lips, tongue, or throat.',
      dosage: 'Take each dose with a full glass (8 ounces) of water. Nexium should be taken at least one hour before a meal.Do not crush or chew a delayed-release capsule. However to make swallowing easier, you may open the capsule and sprinkle the medicine into a spoonful of pudding or applesauce. Swallow right away without chewing. Do not save the mixture for later use.',
    },
    { 
      id: 23,
      price: 43.0,
      name: 'Latanoprost',
      image:'https://wellonapharma.com/admincms/product_img/product_actual_img/latanoprost-eye-drops_1486634880.jpg',
     description: 'A  Latanoprost is a drug that is not branded but is similar to a branded or reference listed drug in terms of dosage, administration and performance.According to guidelines from the United States Food and Drug Administration (FDA), the generic drug must have the same active ingredient as the brand name drug as well as the same dosage, strength, safety, conditions of use and route of administration.',
      sideEffects: 'An allergic reaction could happen with any drug. That can range from itching and rash all the way to a life-threatening anaphylactic reaction.',
      dosage: 'Drug in dosage form, safety, strength, route of administration, quality, performance characteristics,  intended use.'
    },
    { 
      id: 24,
      price: 51.0,
      name: 'Mupirocin',
      image:'https://www.netmeds.com/images/product-v1/600x600/803922/mupricon_2_ointment_5gm_398927_0_0.jpg',
      description: 'Mupirocin is a proton pump inhibitor that decreases the amount of acid produced in the stomach.Mupirocin is used to treat symptoms of gastroesophageal reflux disease (GERD) and other conditions involving excessive stomach acid such as Zollinger-Ellison syndrome. It is also used to promote healing of erosive esophagitis (damage to your esophagus caused by stomach acid).Nexium may also be given to prevent gastric ulcer caused by infection with Helicobacter pylori (H. pylori), or by the use of nonsteroidal anti-inflammatory drugs (NSAIDs).',
      sideEffects: 'Get emergency medical help if you have signs of an allergic reaction ro Mupirocin: hives; difficulty breathing; swelling of your face, lips, tongue, or throat.',
      dosage: 'Take each dose with a full glass (8 ounces) of water. Mupirocin should be taken at least one hour before a meal.Do not crush or chew a delayed-release capsule. However to make swallowing easier, you may open the capsule and sprinkle the medicine into a spoonful of pudding or applesauce. Swallow right away without chewing. Do not save the mixture for later use.',
    },
  ];